#! /usr/bin/bash

# opens Application
cmd - return : open /Applications/Warp.app
# cmd - return : open /Applications/iTerm.app
alt - a : open /Applications/Asana.app
alt - p : open /Applications/PhpStorm.app
alt - b : open /Applications/Google\ Chrome.app
alt - s : open /Applications/Skype.app
alt - f : open /System/Library/CoreServices/Finder.app
#alt - e : open /Applications/Visual\ Studio\ Code.app
alt - m : open /Applications/Spotify.app
# Source 
# https://programmer.ink/think/tile-desktop-under-mac-yabai.html

# Switch back to the nearest desktop
alt - x : yabai -m space --focus recent

shift + alt - a : yabai -m config layout bsp
shift + alt - f : yabai -m window --toggle topmost; yabai -m window --toggle zoom-fullscreen; yabai -m window --toggle topmost

# Toggle split orientation of the selected windows node
shift + lalt - s : yabai -m window --toggle split


# focus window
ctrl + alt- left : yabai -m window --focus west
ctrl + alt - down : yabai -m window --focus south
ctrl + alt - up : yabai -m window --focus north
ctrl + alt - right : yabai -m window --focus east

# move window
alt + cmd - left : yabai -m window --warp west
alt + cmd - down : yabai -m window --warp south
alt + cmd - up : yabai -m window --warp north
alt + cmd - right : yabai -m window --warp east


# send window to desktop and follow focus
shift + alt - 1 : yabai -m window --space  1; yabai -m space --focus 1
shift + alt - 2 : yabai -m window --space  2; yabai -m space --focus 2
shift + alt - 3 : yabai -m window --space  3; yabai -m space --focus 3
shift + alt - 4 : yabai -m window --space  4; yabai -m space --focus 4
shift + alt - 5 : yabai -m window --space  5; yabai -m space --focus 5
shift + alt - 6 : yabai -m window --space  6; yabai -m space --focus 6
shift + alt - 7 : yabai -m window --space  7; yabai -m space --focus 7
shift + alt - 8 : yabai -m window --space  8; yabai -m space --focus 8
shift + alt - 9 : yabai -m window --space  9; yabai -m space --focus 9

# resize window
ctrl + alt + cmd - left : yabai -m window --resize left:-50:0; yabai -m window --resize right:-50:0
ctrl + alt + cmd - down : yabai -m window --resize bottom:0:50; yabai -m window --resize top:0:50
ctrl + alt + cmd - up : yabai -m window --resize top:0:-50; yabai -m window --resize bottom:0:-50
ctrl + alt + cmd - right : yabai -m window --resize right:50:0; yabai -m window --resize left:50:0

# Equalize size of windows
shift + alt - 0 : yabai -m space --balance


# Restart Yabai
shift + alt - r : /usr/bin/env osascript <<< "display notification \"Restarting Yabai\" with title \"Yabai\""; launchctl kickstart -k "gui/${UID}/homebrew.mxcl.yabai"

