#! /usr/bin/bash

# opens Applecation
# alt - a : open /Applications/iTerm.app
# open terminal, blazingly fast compared to iTerm/Hyper
cmd - return : open /Applications/Alacritty.app
alt - p : open /Applications/PhpStorm.app
alt - x : open /Applications/Google Chrome.app
alt - s : open /Applications/Skype.app
alt - n : open /Applications/Notes.app
alt - f : open /System/Library/CoreServices/Finder.app/
