#!/usr/bin/env sh

#https://programmer.ink/think/tile-desktop-under-mac-yabai.html

# ====== Variables =============================


# ===== Loading Scripting Additions ============

# See: https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#macos-big-sur---automatically-load-scripting-addition-on-startup
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# ===== Tiling setting =========================

yabai -m config window_origin_display       default
yabai -m config window_placement            second_child

yabai -m config window_border               of
yabai -m config window_border_width         1
yabai -m config active_window_border_color  0xff775759
yabai -m config normal_window_border_color  0xff555555
yabai -m config insert_feedback_color       0xffd75f5f

# Auto balance all windows always occupy the same space
yabai -m config auto_balance                off
# If auto balancing is disabled, this property defines the amount of space occupied by the new window. 0.5 means that the old window occupies 50%
yabai -m config split_ratio                 0.50
# The mouse modifier button means that you can use the mouse to modify the window size alone by pressing this button
yabai -m config mouse_modifier               fn
# fn + left key movement
yabai -m config mouse_action1               move
# fn + right click
yabai -m config mouse_action2               resize
yabai -m config mouse_drop_action           swap
# Focus follow mouse default off: turn off autoraise: Auto Lift autofocus: Auto Focus
#yabai -m config focus_follows_mouse          autofocus
# Sets whether the mouse follows the current active window. The default is off: off: on: on
# yabai -m config mouse_follows_focus          off

# Floating window problem at the top
yabai -m config window_topmost               on
# Modify window shadow on: open off: close float: only show the shadow of floating window
yabai -m config window_shadow                float

# Window transparency settings
yabai -m config window_opacity               off
# Configure the opacity of the active window
yabai -m config active_window_opacity        1.0             
yabai -m config normal_window_opacity        0.9
yabai -m config window_opacity_duration      0.0

# general space settings
yabai -m config layout                      bsp
yabai -m config top_padding                 5
yabai -m config bottom_padding              5
yabai -m config left_padding                5
yabai -m config right_padding               5
yabai -m config window_gap                  4

# Add 20 padding at the top and 0 padding at the bottom of each space on the main display
# yabai -m config external_bar main:20:0
# Add a 0 fill at the top and a 0 fill at the bottom of each space on all displays
yabai -m config external_bar all:0:5

# Do not manage some apps which are not resizable
yabai -m rule --add app="^(Local|Skype|Calculator|VLC|System Preferences|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|WhatsApp)$" manage=off

# ===== Rules ==================================
yabai -m rule --add label="Finder" app="^Finder$" manage=off
yabai -m rule --add label="TablePlus" app="^TablePlus" manage=off
yabai -m rule --add label="Skype" app="^Skype" manage=off
yabai -m rule --add label="Spotify" app="^Spotify" manage=off
yabai -m rule --add label="Music" app="^Music" manage=off
yabai -m rule --add label="Alfred" app="^Alfred$" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="System Preferences" app="^System Preferences$" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off

# ===== Signals ================================

yabai -m signal --add event=application_front_switched action="${ubersicht_spaces_refresh_command}"
yabai -m signal --add event=display_changed action="${ubersicht_spaces_refresh_command}"
yabai -m signal --add event=space_changed action="${ubersicht_spaces_refresh_command}"
yabai -m signal --add event=window_created action="${ubersicht_spaces_refresh_command}"
yabai -m signal --add event=window_destroyed action="${ubersicht_spaces_refresh_command}"
yabai -m signal --add event=window_focused action="${ubersicht_spaces_refresh_command}"
yabai -m signal --add event=window_title_changed action="${ubersicht_spaces_refresh_command}"


yabai -m space 1 --label Code
yabai -m space 2 --label Web
yabai -m space 3 --label Manager
yabai -m space 4 --label Music
yabai -m space 5 --label misc

echo "yabai configuration loaded.."
